// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vofqmauiwapfwkbzabbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZnFtYXVpd2FwZndrYnphYmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2ODgzNDAsImV4cCI6MjA5MDI2NDM0MH0.FqQWS5RV3Bgy21BeCfQVnCERttN8qopVrKdqd6PRxBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});